# Generated by Django 5.1.7 on 2025-03-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mubsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='books/pdfs/'),
        ),
    ]
