# Generated by Django 5.1.7 on 2025-03-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mubsapp', '0003_softwarecategory_software_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='software_covers/'),
        ),
    ]
