# Generated by Django 5.1.7 on 2025-03-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mubsapp', '0005_alter_software_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='cover',
            field=models.ImageField(blank=True, default='admin.png', null=True, upload_to='software_files/'),
        ),
    ]
