# Generated by Django 5.1.7 on 2025-03-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mubsapp', '0008_alter_software_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='size',
            field=models.FloatField(default=0.0),
        ),
    ]
