# Generated by Django 5.1.7 on 2025-03-20 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mubsapp', '0011_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
