# Generated by Django 5.1.7 on 2025-03-20 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mubsapp', '0013_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='old_cart',
        ),
    ]
